import { useState, useEffect, useRef } from "react";

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Playfair+Display:ital,wght@0,700;0,900;1,400&family=IBM+Plex+Mono:wght@400;700&family=Righteous&family=DM+Mono:wght@400;500&family=Unbounded:wght@700;900&family=Instrument+Serif:ital@1&family=Space+Grotesk:wght@300;400;700&family=Syne:wght@700;800&family=Fraunces:ital,wght@1,700&display=swap');
*{box-sizing:border-box;margin:0;padding:0;}
body{background:#0A0A0A;font-family:'DM Mono',monospace;color:#EEE;}
::-webkit-scrollbar{width:2px;height:2px;}
::-webkit-scrollbar-thumb{background:#2A2A2A;}
button,input{outline:none;cursor:pointer;}
@keyframes spin{from{transform:rotate(0)}to{transform:rotate(360deg)}}
@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.4}}
@keyframes blink{0%,100%{opacity:1}50%{opacity:0}}
@keyframes aurora{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}}
@keyframes neonPulse{0%,100%{text-shadow:0 0 4px #ff2d78,0 0 12px #ff2d7844}50%{text-shadow:0 0 2px #ff2d78}}
@keyframes scanV{from{top:-100%}to{top:100%}}
@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}
@keyframes breathe{0%,100%{transform:scale(1)}50%{transform:scale(1.05)}}
@keyframes dotB{0%,80%,100%{transform:translateY(0)}40%{transform:translateY(-5px)}}
`;

// ── Style palettes ────────────────────────────────────────────────────
const STYLES = {
  Brutalist: {name:"Brutalist", color:"#FF4040", bg:"#FFFEF0", text:"#000"},
  Glass:     {name:"Glass",     color:"#7c3aed", bg:"#1a1a2e", text:"#fff"},
  Synthwave: {name:"Synthwave", color:"#FF2D78", bg:"#0D0021", text:"#FF2D78"},
  Editorial: {name:"Editorial", color:"#1A1A1A", bg:"#FDF8F0", text:"#1A1A1A"},
  Playful:   {name:"Playful",   color:"#FF6B9D", bg:"#FFF0F5", text:"#333"},
  Luxury:    {name:"Luxury",    color:"#C4A96A", bg:"#FAFAF8", text:"#1A1A14"},
  Cyberpunk: {name:"Cyberpunk", color:"#00FFFF", bg:"#0A0A12", text:"#00FFFF"},
  Soft:      {name:"Soft",      color:"#C9B8F0", bg:"#F0EEF8", text:"#5A4A7A"},
  Swiss:     {name:"Swiss",     color:"#E63311", bg:"#F2F0EB", text:"#1A1A1A"},
  DarkEdit:  {name:"Dark Edit", color:"#C4A96A", bg:"#0E0E0C", text:"#F8F4EE"},
  Material:  {name:"Material",  color:"#6750A4", bg:"#FFFFFF", text:"#1C1B1F"},
  Newspaper: {name:"Newspaper", color:"#1A1A1A", bg:"#F5F2E8", text:"#1A1A1A"},
};

// ══════════════════════════════════════════════════════════════════════
// BUTTON — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Buttons = {
  Brutalist: ()=> {const[h,setH]=useState(false);return <div style={{background:"#FFFEF0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:h?"#FF4040":"#000",color:h?"#000":"#FFFEF0",border:"none",padding:"8px 18px",fontFamily:"'IBM Plex Mono',monospace",fontSize:9,letterSpacing:3,cursor:"pointer",transition:"all 0.1s"}}>SUBMIT →</button></div>;},
  Glass:     ()=> {const[h,setH]=useState(false);return <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:h?"rgba(255,255,255,0.18)":"rgba(255,255,255,0.08)",backdropFilter:"blur(8px)",border:"1px solid rgba(255,255,255,0.2)",borderRadius:8,padding:"8px 18px",color:"rgba(255,255,255,0.9)",fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:9,cursor:"pointer",transition:"all 0.2s",letterSpacing:0.5}}>Action</button></div>;},
  Synthwave: ()=> <div style={{background:"#0D0021",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button style={{background:"transparent",border:"1px solid #FF2D78",padding:"8px 18px",color:"#FF2D78",fontFamily:"'Bebas Neue',sans-serif",fontSize:11,letterSpacing:4,cursor:"pointer",textShadow:"0 0 8px #FF2D7888",boxShadow:"0 0 12px #FF2D7833,inset 0 0 12px #FF2D7811"}}>LAUNCH</button></div>,
  Editorial: ()=> {const[h,setH]=useState(false);return <div style={{background:"#FDF8F0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:"transparent",border:`1px solid ${h?"#1A1A1A":"#CCC"}`,padding:"7px 18px",color:"#1A1A1A",fontFamily:"'Playfair Display',serif",fontStyle:"italic",fontSize:10,cursor:"pointer",letterSpacing:1,transition:"border-color 0.2s"}}>Read More</button></div>;},
  Playful:   ()=> {const[h,setH]=useState(false);return <div style={{background:"linear-gradient(135deg,#FFF0F5,#F0F5FF)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:h?"#FF6B9D":"transparent",border:"2px solid #FF6B9D",borderRadius:50,padding:"7px 18px",color:h?"white":"#FF6B9D",fontFamily:"'Righteous',sans-serif",fontSize:9,letterSpacing:1,cursor:"pointer",transition:"all 0.2s",boxShadow:h?"0 4px 14px #FF6B9D66":"none"}}>Create ✦</button></div>;},
  Luxury:    ()=> <div style={{background:"#FAFAF8",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button style={{background:"transparent",border:"1px solid #C4A96A",padding:"7px 20px",color:"#C4A96A",fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:9,letterSpacing:3,cursor:"pointer"}}>Discover</button></div>,
  Cyberpunk: ()=> {const[h,setH]=useState(false);return <div style={{background:"#0A0A12",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:h?"#00FFFF22":"transparent",border:"1px solid #00FFFF",padding:"8px 18px",color:"#00FFFF",fontFamily:"'IBM Plex Mono',monospace",fontSize:9,letterSpacing:3,cursor:"pointer",transition:"all 0.2s",boxShadow:h?"0 0 16px #00FFFF44":"none",clipPath:"polygon(4px 0%,100% 0%,calc(100% - 4px) 100%,0% 100%)"}}>EXECUTE</button></div>;},
  Soft:      ()=> {const[p,setP]=useState(false);return <div style={{background:"#E8E4F0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseDown={()=>setP(true)} onMouseUp={()=>setP(false)} style={{background:p?"#D0CCE4":"#E8E4F0",border:"none",borderRadius:50,padding:"8px 20px",color:"#7A6A9A",fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:9,cursor:"pointer",boxShadow:p?"inset 2px 2px 5px #C0BCD4":"3px 3px 8px #C0BCD4,-2px -2px 5px #FFF",transition:"all 0.1s",letterSpacing:0.5}}>Play ▶</button></div>;},
  Swiss:     ()=> {const[h,setH]=useState(false);return <div style={{background:"#F2F0EB",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:h?"#E63311":"#1A1A1A",color:"#F2F0EB",border:"none",padding:"8px 20px",fontFamily:"'Unbounded',sans-serif",fontWeight:700,fontSize:8,letterSpacing:1,cursor:"pointer",transition:"background 0.15s"}}>SUBMIT</button></div>;},
  DarkEdit:  ()=> <div style={{background:"#0E0E0C",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button style={{background:"transparent",border:"1px solid #C4A96A",padding:"7px 18px",color:"#C4A96A",fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:9,letterSpacing:2,cursor:"pointer"}}>Explore →</button></div>,
  Material:  ()=> {const[h,setH]=useState(false);return <div style={{background:"#FFF",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:h?"#7965AF":"#6750A4",color:"#FFF",border:"none",borderRadius:50,padding:"8px 20px",fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:9,cursor:"pointer",boxShadow:h?"0 4px 12px #6750A455":"0 2px 6px #6750A433",transition:"all 0.2s",letterSpacing:0.5}}>Continue</button></div>;},
  Newspaper: ()=> <div style={{background:"#F5F2E8",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><button style={{background:"#1A1A1A",color:"#F5F2E8",border:"none",padding:"7px 16px",fontFamily:"'Playfair Display',serif",fontWeight:700,fontSize:9,cursor:"pointer",letterSpacing:1}}>Read Full Story</button></div>,
};

// ══════════════════════════════════════════════════════════════════════
// CARD — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Cards = {
  Brutalist: ()=> <div style={{background:"#FFFEF0",height:"100%",display:"flex",flexDirection:"column",borderLeft:"4px solid #000"}}><div style={{background:"#000",padding:"4px 8px",fontFamily:"'IBM Plex Mono',monospace",fontSize:7,letterSpacing:2,color:"#FFFEF0"}}>ARTICLE_001</div><div style={{flex:1,padding:"6px 8px",display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:16,color:"#000",letterSpacing:1,lineHeight:1}}>DESIGN<br/>SYSTEMS</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#666",letterSpacing:2}}>READ →</div></div></div>,
  Glass:     ()=> <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"8px"}}><div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(10px)",border:"1px solid rgba(255,255,255,0.15)",borderRadius:10,padding:"10px 12px",width:"100%"}}><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:10,color:"rgba(255,255,255,0.9)",marginBottom:3}}>Glassmorphism</div><div style={{height:1,background:"rgba(255,255,255,0.1)",margin:"4px 0"}}/><div style={{fontSize:7,color:"rgba(255,255,255,0.45)",fontFamily:"'DM Mono',monospace",letterSpacing:1}}>UI PATTERN · 2026</div></div></div>,
  Synthwave: ()=> <div style={{background:"#0D0021",height:"100%",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"8px",borderTop:"1px solid #FF2D78"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#FF2D78",letterSpacing:3}}>VOL://0x08</div><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:18,color:"#FF2D78",letterSpacing:2,lineHeight:1,textShadow:"0 0 12px #FF2D7888"}}>NIGHT<br/>RIDER</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#00E5FF",letterSpacing:2}}>ACCESS →</div></div>,
  Editorial: ()=> <div style={{background:"#FDF8F0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"8px 10px",borderBottom:"2px solid #1A1A1A"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:3,color:"#999",textTransform:"uppercase"}}>Feature</div><div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:13,color:"#1A1A1A",lineHeight:1,marginBottom:3}}>The Grid &<br/>Typography</div><div style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize:7,color:"#666",lineHeight:1.5}}>On structure and freedom in modern design.</div></div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,color:"#999",letterSpacing:2}}>JUNE 2026</div></div>,
  Playful:   ()=> <div style={{background:"linear-gradient(135deg,#FFF0F5,#F5F0FF)",height:"100%",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"8px",borderRadius:0}}><div style={{fontSize:18,marginBottom:2}}>🎨</div><div><div style={{fontFamily:"'Righteous',sans-serif",fontSize:11,color:"#D63384",marginBottom:2}}>Creative Studio</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:300,fontSize:7,color:"#888",lineHeight:1.5}}>Make something beautiful today</div></div><div style={{background:"#FF6B9D",color:"white",borderRadius:50,padding:"3px 8px",fontSize:7,fontFamily:"'Righteous',sans-serif",letterSpacing:1,alignSelf:"flex-start"}}>Explore</div></div>,
  Luxury:    ()=> <div style={{background:"#FAFAF8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"8px 12px",borderLeft:"1px solid #C4A96A"}}><div style={{fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:7,letterSpacing:4,color:"#C4A96A",textTransform:"uppercase"}}>Collection</div><div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:14,color:"#1A1A14",lineHeight:1,marginBottom:4}}>Maison<br/>Dorée</div><div style={{width:20,height:1,background:"#C4A96A"}}/></div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:3,color:"#C4A96A"}}>VIEW MORE</div></div>,
  Cyberpunk: ()=> <div style={{background:"#0A0A12",height:"100%",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"8px",borderLeft:"2px solid #00FFFF",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,right:0,width:30,height:30,background:"radial-gradient(circle,#00FFFF14,transparent)",filter:"blur(6px)"}}/><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#00FFFF",letterSpacing:2,opacity:0.7}}>NODE://44</div><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:16,color:"#00FFFF",letterSpacing:2,textShadow:"0 0 10px #00FFFF88"}}>NEURAL<br/>LINK</div><div style={{display:"flex",gap:3}}>{[1,2,3].map(i=><div key={i} style={{width:5,height:5,borderRadius:1,background:"#00FFFF",opacity:0.6}}/>)}</div></div>,
  Soft:      ()=> <div style={{background:"#F0EEF8",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:6,padding:"8px"}}><div style={{width:36,height:36,borderRadius:12,background:"linear-gradient(135deg,#C9B8F0,#E8D4F0)",boxShadow:"3px 3px 8px #C9B8F066,-1px -1px 4px #FFF",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16}}>✦</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:9,color:"#5A4A7A",textAlign:"center"}}>Soft Design</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:300,fontSize:7,color:"#9A8ABB",textAlign:"center"}}>gentle · calm</div></div>,
  Swiss:     ()=> <div style={{background:"#F2F0EB",height:"100%",display:"flex",flexDirection:"column"}}><div style={{height:20,background:"#E63311",display:"flex",alignItems:"center",padding:"0 8px"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,letterSpacing:3,color:"#F2F0EB",textTransform:"uppercase"}}>Project</div></div><div style={{flex:1,padding:"6px 8px",display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{fontFamily:"'Unbounded',sans-serif",fontWeight:900,fontSize:13,color:"#1A1A1A",lineHeight:1,letterSpacing:-0.5}}>NEUE<br/>GRAFIK</div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#888",letterSpacing:2}}>2026</span><div style={{width:14,height:14,borderRadius:"50%",background:"#E63311"}}/></div></div></div>,
  DarkEdit:  ()=> <div style={{background:"#0E0E0C",height:"100%",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"8px 10px",borderBottom:"2px solid #C4A96A"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:3,color:"#C4A96A",textTransform:"uppercase"}}>Issue 08</div><div><div style={{fontFamily:"'Playfair Display',serif",fontStyle:"italic",fontSize:14,color:"#F8F4EE",lineHeight:0.95,marginBottom:3}}>The Golden<br/>Standard</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#555",lineHeight:1.5}}>A meditation on timeless craft.</div></div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,color:"#C4A96A",letterSpacing:2}}>READ →</div></div>,
  Material:  ()=> {const[h,setH]=useState(false);return <div onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:"#FFF",height:"100%",display:"flex",flexDirection:"column",boxShadow:h?"0 6px 18px rgba(0,0,0,0.15)":"0 2px 6px rgba(0,0,0,0.08)",transition:"box-shadow 0.3s"}}><div style={{height:28,background:"linear-gradient(135deg,#6750A4,#9C4DC4)",display:"flex",alignItems:"center",padding:"0 8px"}}><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:9,color:"white"}}>Material Card</div></div><div style={{flex:1,padding:"8px",display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:"#49454E",lineHeight:1.5}}>Elevation responds to interaction context.</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:7,color:"#6750A4",fontWeight:700,letterSpacing:0.5}}>Learn more →</div></div></div>;},
  Newspaper: ()=> <div style={{background:"#F5F2E8",height:"100%",padding:"6px 8px",borderTop:"2px solid #1A1A1A"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:3,color:"#888",marginBottom:3}}>LOCAL NEWS</div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:11,color:"#1A1A1A",lineHeight:1.1,marginBottom:3}}>City Council Approves New Design District</div><div style={{fontFamily:"'Instrument Serif',serif",fontSize:7,color:"#555",lineHeight:1.5}}>Plans include 40 new studios along the waterfront...</div></div>,
};

// ══════════════════════════════════════════════════════════════════════
// INPUT — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Inputs = {
  Brutalist: ()=> {const[v,setV]=useState("");const[f,setF]=useState(false);return <div style={{background:"#FFFEF0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:4}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,letterSpacing:3,color:"#000",textTransform:"uppercase"}}>Search</div><div style={{display:"flex",borderBottom:`3px solid ${f?"#FF4040":"#000"}`,transition:"border-color 0.15s"}}><input value={v} onChange={e=>setV(e.target.value)} onFocus={()=>setF(true)} onBlur={()=>setF(false)} placeholder="Type here..." style={{flex:1,background:"transparent",border:"none",fontFamily:"'IBM Plex Mono',monospace",fontSize:10,color:"#000",padding:"4px 0",letterSpacing:0.5}}/><span style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:10,color:f?"#FF4040":"#000"}}>→</span></div></div>;},
  Glass:     ()=> {const[f,setF]=useState(false);return <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"0 12px"}}><div style={{width:"100%",position:"relative"}}><input placeholder="Search..." onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{width:"100%",background:"rgba(255,255,255,0.07)",border:`1px solid rgba(255,255,255,${f?0.35:0.12})`,borderRadius:8,padding:"7px 10px 7px 28px",color:"rgba(255,255,255,0.9)",fontFamily:"'Space Grotesk',sans-serif",fontSize:9,backdropFilter:"blur(4px)",transition:"border-color 0.2s"}}/><span style={{position:"absolute",left:9,top:"50%",transform:"translateY(-50%)",fontSize:10,color:"rgba(255,255,255,0.4)"}}>⌕</span></div></div>;},
  Synthwave: ()=> {const[f,setF]=useState(false);return <div style={{background:"#0D0021",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"0 12px"}}><div style={{width:"100%",position:"relative"}}><input placeholder="SEARCH_" onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{width:"100%",background:"transparent",border:`1px solid ${f?"#FF2D78":"#333"}`,padding:"7px 10px",color:"#FF2D78",fontFamily:"'IBM Plex Mono',monospace",fontSize:8,letterSpacing:2,transition:"border-color 0.2s",boxShadow:f?"0 0 10px #FF2D7833":"none"}}/>{f&&<span style={{position:"absolute",right:8,top:"50%",transform:"translateY(-50%)",width:8,height:12,background:"#FF2D78",animation:"blink 0.8s step-end infinite"}}/>}</div></div>;},
  Editorial: ()=> {const[f,setF]=useState(false);return <div style={{background:"#FDF8F0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:4}}><label style={{fontFamily:"'Playfair Display',serif",fontStyle:"italic",fontSize:9,color:f?"#1A1A1A":"#999",transition:"color 0.2s"}}>Your name</label><input onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{background:"transparent",border:"none",borderBottom:`1px solid ${f?"#1A1A1A":"#DDD"}`,fontFamily:"'Playfair Display',serif",fontSize:11,color:"#1A1A1A",padding:"4px 0",transition:"border-color 0.2s"}}/></div>;},
  Playful:   ()=> {const[f,setF]=useState(false);return <div style={{background:"linear-gradient(135deg,#FFF0F5,#F5F0FF)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"0 12px"}}><div style={{width:"100%",position:"relative"}}><input placeholder="Search..." onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{width:"100%",background:"white",border:`2px solid ${f?"#FF6B9D":"#FFD6E7"}`,borderRadius:50,padding:"6px 12px 6px 28px",color:"#333",fontFamily:"'Space Grotesk',sans-serif",fontSize:9,transition:"all 0.2s",boxShadow:f?"0 4px 12px #FF6B9D33":"none"}}/><span style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",fontSize:10,color:"#FFB7C5"}}>⌕</span></div></div>;},
  Luxury:    ()=> {const[f,setF]=useState(false);return <div style={{background:"#FAFAF8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 14px",gap:5}}><label style={{fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:7,letterSpacing:4,color:"#C4A96A",textTransform:"uppercase"}}>Your Name</label><input onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{background:"transparent",border:"none",borderBottom:`1px solid ${f?"#C4A96A":"#D4C4A0"}`,fontFamily:"'Playfair Display',serif",fontSize:11,color:"#1A1A14",padding:"4px 0",transition:"border-color 0.2s"}}/></div>;},
  Cyberpunk: ()=> {const[f,setF]=useState(false);return <div style={{background:"#0A0A12",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"0 12px"}}><div style={{width:"100%",position:"relative"}}><input placeholder="QUERY://" onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{width:"100%",background:"transparent",border:`1px solid ${f?"#00FFFF":"#00FFFF44"}`,padding:"7px 10px",color:"#00FFFF",fontFamily:"'IBM Plex Mono',monospace",fontSize:8,letterSpacing:2,transition:"all 0.2s",clipPath:"polygon(4px 0%,100% 0%,calc(100% - 4px) 100%,0% 100%)",boxShadow:f?"0 0 12px #00FFFF33":"none"}}/></div></div>;},
  Soft:      ()=> {const[f,setF]=useState(false);return <div style={{background:"#E8E4F0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"0 12px"}}><input placeholder="Search..." onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{width:"100%",background:f?"#E8E4F0":"#E0DCF0",border:"none",borderRadius:50,padding:"7px 14px",color:"#5A4A7A",fontFamily:"'Space Grotesk',sans-serif",fontSize:9,boxShadow:f?"inset 3px 3px 6px #C0BCD4,inset -1px -1px 3px #FFF":"3px 3px 8px #C0BCD4,-2px -2px 5px #FFF",transition:"all 0.2s"}}/></div>;},
  Swiss:     ()=> {const[f,setF]=useState(false);return <div style={{background:"#F2F0EB",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:4}}><label style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:4,color:"#888",textTransform:"uppercase"}}>Search</label><input onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{background:"transparent",border:"none",borderBottom:`2px solid ${f?"#E63311":"#1A1A1A"}`,fontFamily:"'Unbounded',sans-serif",fontWeight:700,fontSize:10,color:"#1A1A1A",padding:"4px 0",transition:"border-color 0.2s"}}/></div>;},
  DarkEdit:  ()=> {const[f,setF]=useState(false);return <div style={{background:"#0E0E0C",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:5}}><label style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:4,color:"#C4A96A",textTransform:"uppercase"}}>Search</label><input onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{background:"transparent",border:"none",borderBottom:`1px solid ${f?"#C4A96A":"#333"}`,fontFamily:"'Playfair Display',serif",fontStyle:"italic",fontSize:11,color:"#F8F4EE",padding:"4px 0",transition:"border-color 0.2s"}}/></div>;},
  Material:  ()=> {const[f,setF]=useState(false);return <div style={{background:"#FFF",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"0 12px"}}><div style={{width:"100%",position:"relative"}}><input placeholder="Search" onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{width:"100%",background:f?"#EDE7F6":"#F3EDF7",border:"none",borderBottom:`2px solid ${f?"#6750A4":"transparent"}`,borderRadius:"4px 4px 0 0",padding:"10px 12px 10px 30px",color:"#1C1B1F",fontFamily:"'Space Grotesk',sans-serif",fontSize:9,transition:"all 0.2s"}}/><span style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",fontSize:11,color:f?"#6750A4":"#79747E"}}>⌕</span></div></div>;},
  Newspaper: ()=> {const[f,setF]=useState(false);return <div style={{background:"#F5F2E8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:4}}><label style={{fontFamily:"'Playfair Display',serif",fontWeight:700,fontSize:8,color:"#1A1A1A",letterSpacing:1}}>Search the Archive</label><input onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{background:"transparent",border:`1px solid ${f?"#1A1A1A":"#CCC"}`,padding:"5px 8px",fontFamily:"'IBM Plex Mono',monospace",fontSize:8,color:"#1A1A1A",transition:"border-color 0.2s"}}/></div>;},
};

// ══════════════════════════════════════════════════════════════════════
// BADGE — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Badges = {
  Brutalist: ()=> <div style={{background:"#FFFEF0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{[{l:"LIVE",bg:"#000",c:"#FFFEF0"},{l:"NEW",bg:"#FF4040",c:"#000"},{l:"HOT",bg:"#FFFEF0",c:"#000",b:"3px solid #000"}].map((b,i)=><div key={i} style={{background:b.bg,color:b.c,border:b.b||"none",padding:"3px 8px",fontFamily:"'IBM Plex Mono',monospace",fontSize:7,letterSpacing:2,fontWeight:700}}>{b.l}</div>)}</div>,
  Glass:     ()=> <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{["Live","Beta","New"].map((l,i)=><div key={i} style={{background:`rgba(${[124,58,237,0.25,100,200,255,0.2,34,197,94,0.2][i*4]},${[124,58,237,0.25,100,200,255,0.2,34,197,94,0.2][i*4+1]},${[124,58,237,0.25,100,200,255,0.2,34,197,94,0.2][i*4+2]},${[124,58,237,0.25,100,200,255,0.2,34,197,94,0.2][i*4+3]})`,border:"1px solid rgba(255,255,255,0.2)",borderRadius:6,padding:"3px 9px",color:"rgba(255,255,255,0.85)",fontFamily:"'Space Grotesk',sans-serif",fontSize:7,fontWeight:700,backdropFilter:"blur(4px)"}}>{l}</div>)}</div>,
  Synthwave: ()=> <div style={{background:"#0D0021",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{[{l:"LIVE",c:"#FF2D78"},{l:"HOT",c:"#00E5FF"},{l:"NEW",c:"#FFD700"}].map((b,i)=><div key={i} style={{border:`1px solid ${b.c}`,padding:"3px 8px",color:b.c,fontFamily:"'Bebas Neue',sans-serif",fontSize:8,letterSpacing:3,textShadow:`0 0 6px ${b.c}88`,boxShadow:`0 0 8px ${b.c}22`}}>{b.l}</div>)}</div>,
  Editorial: ()=> <div style={{background:"#FDF8F0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{[{l:"Feature",style:"italic"},{l:"Review",style:"normal"},{l:"Essay",style:"italic"}].map((b,i)=><div key={i} style={{border:"1px solid #1A1A1A",padding:"3px 8px",color:"#1A1A1A",fontFamily:"'Playfair Display',serif",fontSize:8,fontStyle:b.style,letterSpacing:0.5}}>{b.l}</div>)}</div>,
  Playful:   ()=> <div style={{background:"linear-gradient(135deg,#FFF0F5,#F5F0FF)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{[{l:"✦ New",c:"#FF6B9D"},{l:"🔥 Hot",c:"#FF8C42"},{l:"★ Top",c:"#FFD700"}].map((b,i)=><div key={i} style={{background:`${b.c}22`,border:`2px solid ${b.c}`,borderRadius:50,padding:"3px 9px",color:b.c,fontFamily:"'Righteous',sans-serif",fontSize:7,letterSpacing:0.5}}>{b.l}</div>)}</div>,
  Luxury:    ()=> <div style={{background:"#FAFAF8",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{["Collection","Edition","Reserve"].map((l,i)=><div key={i} style={{border:"1px solid #C4A96A",padding:"3px 10px",color:"#C4A96A",fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:7,letterSpacing:2}}>{l}</div>)}</div>,
  Cyberpunk: ()=> <div style={{background:"#0A0A12",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{[{l:"SYS",c:"#00FFFF"},{l:"ERR",c:"#FF2D78"},{l:"RUN",c:"#00FF88"}].map((b,i)=><div key={i} style={{background:`${b.c}14`,border:`1px solid ${b.c}`,padding:"3px 8px",color:b.c,fontFamily:"'IBM Plex Mono',monospace",fontSize:7,letterSpacing:2,boxShadow:`0 0 6px ${b.c}33`}}>{b.l}</div>)}</div>,
  Soft:      ()=> <div style={{background:"#F0EEF8",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{[{l:"Active",c:"#A8E6CF"},{l:"Pause",c:"#FFD3B6"},{l:"Done",c:"#C9B8F0"}].map((b,i)=><div key={i} style={{background:b.c,borderRadius:50,padding:"3px 10px",color:"#5A4A7A",fontFamily:"'Space Grotesk',sans-serif",fontSize:7,fontWeight:700,boxShadow:`2px 2px 6px ${b.c}88`}}>{b.l}</div>)}</div>,
  Swiss:     ()=> <div style={{background:"#F2F0EB",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{[{l:"A",bg:"#E63311"},{l:"B",bg:"#1A1A1A"},{l:"C",bg:"#888"}].map((b,i)=><div key={i} style={{background:b.bg,color:"#F2F0EB",width:28,height:28,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Unbounded',sans-serif",fontWeight:900,fontSize:9}}>{b.l}</div>)}</div>,
  DarkEdit:  ()=> <div style={{background:"#0E0E0C",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{["Vol.08","Essay","Culture"].map((l,i)=><div key={i} style={{border:`1px solid ${i===0?"#C4A96A":"#333"}`,padding:"3px 8px",color:i===0?"#C4A96A":"#555",fontFamily:"'IBM Plex Mono',monospace",fontSize:6,letterSpacing:2}}>{l}</div>)}</div>,
  Material:  ()=> <div style={{background:"#FFF",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{[{l:"Filled",bg:"#6750A4",c:"#FFF"},{l:"Outlined",bg:"transparent",c:"#6750A4",b:"1px solid #6750A4"},{l:"Tonal",bg:"#EDE7F6",c:"#6750A4"}].map((b,i)=><div key={i} style={{background:b.bg,border:b.b||"none",borderRadius:50,padding:"3px 10px",color:b.c,fontFamily:"'Space Grotesk',sans-serif",fontSize:7,fontWeight:700,letterSpacing:0.5}}>{b.l}</div>)}</div>,
  Newspaper: ()=> <div style={{background:"#F5F2E8",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{["BREAKING","OPINION","SPORTS"].map((l,i)=><div key={i} style={{background:i===0?"#1A1A1A":"transparent",border:i>0?"1px solid #1A1A1A":"none",padding:"3px 7px",color:i===0?"#F5F2E8":"#1A1A1A",fontFamily:"'IBM Plex Mono',monospace",fontSize:6,letterSpacing:1,fontWeight:700}}>{l}</div>)}</div>,
};

// ══════════════════════════════════════════════════════════════════════
// TOGGLE — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Toggles = {
  Brutalist: ()=> {const[on,setOn]=useState(true);return <div style={{background:"#FFFEF0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",gap:8}}>{["Notifications","Dark Mode"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",gap:10,alignItems:"center"}}><span style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:8,color:"#000",letterSpacing:1,width:80}}>{l}</span><div onClick={()=>setOn(o=>!o)} style={{width:30,height:16,background:s?"#000":"transparent",border:"3px solid #000",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:s?"flex-end":"flex-start",padding:1}}><div style={{width:10,height:10,background:s?"#FFFEF0":"#000"}}/></div></div>;})} </div>;},
  Glass:     ()=> {const[on,setOn]=useState(true);return <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:10}}>{["Sync","Blur"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:4,cursor:"pointer"}} onClick={()=>setOn(o=>!o)}><div style={{width:32,height:17,borderRadius:8,background:s?"rgba(124,58,237,0.5)":"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.15)",backdropFilter:"blur(4px)",display:"flex",alignItems:"center",padding:2,justifyContent:s?"flex-end":"flex-start",transition:"all 0.2s"}}><div style={{width:11,height:11,borderRadius:"50%",background:s?"#a78bfa":"rgba(255,255,255,0.3)",transition:"all 0.2s"}}/></div><span style={{fontFamily:"'DM Mono',monospace",fontSize:6,color:"rgba(255,255,255,0.5)",letterSpacing:1}}>{l}</span></div>;})} </div>;},
  Synthwave: ()=> {const[on,setOn]=useState(true);return <div style={{background:"#0D0021",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8}}>{["POWER","BOOST"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",gap:8,alignItems:"center",cursor:"pointer"}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:7,color:"#FF2D78",letterSpacing:2,width:36}}>{l}</span><div style={{width:28,height:14,border:`1px solid ${s?"#FF2D78":"#333"}`,display:"flex",alignItems:"center",padding:2,justifyContent:s?"flex-end":"flex-start",transition:"all 0.2s",boxShadow:s?"0 0 8px #FF2D7844":"none"}}><div style={{width:8,height:8,background:s?"#FF2D78":"#333",transition:"all 0.2s"}}/></div></div>;})} </div>;},
  Editorial: ()=> {const[on,setOn]=useState(true);return <div style={{background:"#FDF8F0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 14px",gap:8}}>{["Subscribe","Alerts"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #E8E0D0",paddingBottom:6,cursor:"pointer"}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'Playfair Display',serif",fontSize:9,color:"#1A1A1A",fontStyle:"italic"}}>{l}</span><div style={{width:28,height:14,borderRadius:7,background:s?"#1A1A1A":"#DDD",display:"flex",alignItems:"center",padding:2,justifyContent:s?"flex-end":"flex-start",transition:"all 0.25s"}}><div style={{width:9,height:9,borderRadius:"50%",background:"#FDF8F0",transition:"all 0.25s"}}/></div></div>;})} </div>;},
  Playful:   ()=> {const[on,setOn]=useState(true);return <div style={{background:"linear-gradient(135deg,#FFF0F5,#F5F0FF)",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8}}>{["Vibes","Music"].map((l,i)=>{const s=i===0?on:!on;const c=i===0?"#FF6B9D":"#B77FFF";return <div key={i} style={{display:"flex",gap:8,alignItems:"center",cursor:"pointer"}} onClick={()=>setOn(o=>!o)}><div style={{width:34,height:18,borderRadius:9,background:s?c:"#E0DBF0",display:"flex",alignItems:"center",padding:3,justifyContent:s?"flex-end":"flex-start",transition:"all 0.3s",boxShadow:s?`0 3px 10px ${c}55`:"none"}}><div style={{width:12,height:12,borderRadius:"50%",background:"white",transition:"all 0.3s cubic-bezier(0.34,1.56,0.64,1)"}}/></div><span style={{fontFamily:"'Righteous',sans-serif",fontSize:9,color:s?c:"#AAA",transition:"color 0.2s"}}>{l}</span></div>;})} </div>;},
  Luxury:    ()=> {const[on,setOn]=useState(true);return <div style={{background:"#FAFAF8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 14px",gap:8}}>{["Notifications","Exclusive"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer",borderBottom:"1px solid #E8E0D0",paddingBottom:6}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:8,color:"#8A7A60",letterSpacing:1}}>{l}</span><div style={{width:26,height:13,borderRadius:6,background:s?"#C4A96A":"#DDD",display:"flex",alignItems:"center",padding:2,justifyContent:s?"flex-end":"flex-start",transition:"all 0.25s"}}><div style={{width:8,height:8,borderRadius:"50%",background:"white",transition:"all 0.25s"}}/></div></div>;})} </div>;},
  Cyberpunk: ()=> {const[on,setOn]=useState(true);return <div style={{background:"#0A0A12",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8}}>{["SYS","NET"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",gap:8,alignItems:"center",cursor:"pointer"}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:7,color:s?"#00FFFF":"#444",letterSpacing:2,width:24,transition:"color 0.2s"}}>{l}</span><div style={{width:28,height:13,border:`1px solid ${s?"#00FFFF":"#333"}`,display:"flex",alignItems:"center",padding:2,justifyContent:s?"flex-end":"flex-start",transition:"all 0.2s",boxShadow:s?"0 0 8px #00FFFF33":"none"}}><div style={{width:7,height:7,background:s?"#00FFFF":"#333",transition:"all 0.2s"}}/></div></div>;})} </div>;},
  Soft:      ()=> {const[on,setOn]=useState(true);return <div style={{background:"#E8E4F0",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:10}}>{["Notifications","Privacy"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",gap:8,alignItems:"center",cursor:"pointer"}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:s?"#5A4A7A":"#AAA",transition:"color 0.2s",width:70}}>{l}</span><div style={{width:32,height:17,borderRadius:8,background:s?"#C9B8F0":"#D0CCE4",display:"flex",alignItems:"center",padding:3,justifyContent:s?"flex-end":"flex-start",boxShadow:s?"inset 2px 2px 4px #A89ECC":"inset 2px 2px 4px #B8B4CC",transition:"all 0.2s"}}><div style={{width:11,height:11,borderRadius:"50%",background:"white",boxShadow:"1px 1px 3px #CCC",transition:"all 0.2s"}}/></div></div>;})} </div>;},
  Swiss:     ()=> {const[on,setOn]=useState(true);return <div style={{background:"#F2F0EB",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:8}}>{["Display","Grid"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer",borderBottom:"1px solid #1A1A1A",paddingBottom:5}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'Unbounded',sans-serif",fontWeight:700,fontSize:7,color:"#1A1A1A",letterSpacing:0.5}}>{l}</span><div style={{width:26,height:12,background:s?"#1A1A1A":"transparent",border:"2px solid #1A1A1A",display:"flex",alignItems:"center",padding:1,justifyContent:s?"flex-end":"flex-start",transition:"all 0.15s"}}><div style={{width:8,height:8,background:s?"#F2F0EB":"#1A1A1A",transition:"all 0.15s"}}/></div></div>;})} </div>;},
  DarkEdit:  ()=> {const[on,setOn]=useState(true);return <div style={{background:"#0E0E0C",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:8}}>{["Newsletter","Alerts"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer",borderBottom:"1px solid #2A2A28",paddingBottom:5}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'Playfair Display',serif",fontStyle:"italic",fontSize:8,color:s?"#C4A96A":"#555",transition:"color 0.2s"}}>{l}</span><div style={{width:26,height:12,borderRadius:6,background:s?"#C4A96A22":"transparent",border:`1px solid ${s?"#C4A96A":"#444"}`,display:"flex",alignItems:"center",padding:2,justifyContent:s?"flex-end":"flex-start",transition:"all 0.25s"}}><div style={{width:7,height:7,borderRadius:"50%",background:s?"#C4A96A":"#444",transition:"all 0.25s"}}/></div></div>;})} </div>;},
  Material:  ()=> {const[on,setOn]=useState(true);return <div style={{background:"#FFF",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:8}}>{["Notifications","Location"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:9,color:"#1C1B1F"}}>{l}</span><div style={{width:34,height:18,borderRadius:9,background:s?"#6750A4":"#E8E0ED",display:"flex",alignItems:"center",padding:3,justifyContent:s?"flex-end":"flex-start",transition:"all 0.2s",boxShadow:s?"0 2px 6px #6750A433":"none"}}><div style={{width:12,height:12,borderRadius:"50%",background:"white",transition:"all 0.2s",boxShadow:"0 1px 3px rgba(0,0,0,0.2)"}}/></div></div>;})} </div>;},
  Newspaper: ()=> {const[on,setOn]=useState(true);return <div style={{background:"#F5F2E8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:7}}>{["Breaking Alerts","Subscription"].map((l,i)=>{const s=i===0?on:!on;return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer",borderBottom:"1px solid #DDD",paddingBottom:5}} onClick={()=>setOn(o=>!o)}><span style={{fontFamily:"'Playfair Display',serif",fontSize:8,color:"#1A1A1A"}}>{l}</span><div style={{width:24,height:12,background:s?"#1A1A1A":"transparent",border:"2px solid #1A1A1A",display:"flex",alignItems:"center",padding:1,justifyContent:s?"flex-end":"flex-start",transition:"background 0.15s"}}><div style={{width:8,height:8,background:s?"#F5F2E8":"#1A1A1A",transition:"background 0.15s"}}/></div></div>;})} </div>;},
};

// ══════════════════════════════════════════════════════════════════════
// LOADER — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Loaders = {
  Brutalist: ()=> <div style={{background:"#FFFEF0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{[0,1,2].map(i=><div key={i} style={{width:12,height:12,border:"3px solid #000",animation:`dotB 1.2s ease-in-out ${i*160}ms infinite`}}/>)}</div>,
  Glass:     ()=> <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:30,height:30,borderRadius:"50%",border:"1px solid rgba(255,255,255,0.1)",borderTop:"2px solid rgba(124,58,237,0.8)",animation:"spin 0.8s linear infinite",boxShadow:"0 0 12px rgba(124,58,237,0.3)"}}/></div>,
  Synthwave: ()=> <div style={{background:"#0D0021",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{[0,1,2,3,4].map(i=><div key={i} style={{width:4,height:4+i*4,background:i%2===0?"#FF2D78":"#00E5FF",animation:`pulse 1s ease-in-out ${i*100}ms infinite`,boxShadow:i%2===0?"0 0 6px #FF2D7888":"0 0 6px #00E5FF88"}}/>)}</div>,
  Editorial: ()=> <div style={{background:"#FDF8F0",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:6}}><div style={{width:50,height:1,background:"#DDD",overflow:"hidden",position:"relative"}}><div style={{position:"absolute",left:"-100%",width:"50%",height:"100%",background:"#1A1A1A",animation:"shimmer 1.2s ease-in-out infinite"}}/></div><div style={{fontFamily:"'Playfair Display',serif",fontStyle:"italic",fontSize:8,color:"#999",letterSpacing:2}}>Loading…</div></div>,
  Playful:   ()=> <div style={{background:"linear-gradient(135deg,#FFF0F5,#F5F0FF)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{["🟣","🟡","🩷"].map((e,i)=><span key={i} style={{fontSize:12,animation:`float ${0.8+i*0.15}s ease-in-out ${i*150}ms infinite`}}>{e}</span>)}</div>,
  Luxury:    ()=> <div style={{background:"#FAFAF8",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8}}><div style={{width:24,height:24,borderRadius:"50%",border:"1px solid #C4A96A",borderTop:"1px solid transparent",animation:"spin 1.5s linear infinite"}}/><div style={{fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:7,color:"#C4A96A",letterSpacing:4}}>please wait</div></div>,
  Cyberpunk: ()=> <div style={{background:"#0A0A12",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:5}}><div style={{width:32,height:32,position:"relative"}}><div style={{position:"absolute",inset:0,border:"1px solid #00FFFF22",borderRadius:0}}/><div style={{position:"absolute",inset:0,border:"1px solid #00FFFF",borderRadius:0,animation:"spin 0.8s linear infinite",clipPath:"polygon(0 0,60% 0,100% 40%,100% 100%,40% 100%,0 60%)"}}/></div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#00FFFF",letterSpacing:3,animation:"pulse 1s ease-in-out infinite"}}>LOADING</div></div>,
  Soft:      ()=> <div style={{background:"#E8E4F0",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}>{[0,1,2].map(i=><div key={i} style={{width:10,height:10,borderRadius:"50%",background:["#C9B8F0","#FFB7C5","#B7D4FF"][i],boxShadow:`2px 2px 6px ${["#C9B8F0","#FFB7C5","#B7D4FF"][i]}88`,animation:`dotB 1.2s ease-in-out ${i*160}ms infinite`}}/>)}</div>,
  Swiss:     ()=> <div style={{background:"#F2F0EB",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:6}}><div style={{width:40,height:3,background:"#EEE",overflow:"hidden",position:"relative"}}><div style={{position:"absolute",left:0,width:"40%",height:"100%",background:"#E63311",animation:"loadSweep 1s ease-in-out infinite"}}/></div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#888",letterSpacing:4}}>LOADING</div></div>,
  DarkEdit:  ()=> <div style={{background:"#0E0E0C",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:7}}><div style={{width:28,height:28,borderRadius:"50%",border:"1px solid #333",borderTop:`1px solid #C4A96A`,animation:"spin 1.5s linear infinite",boxShadow:"0 0 10px #C4A96A33"}}/><div style={{fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:8,color:"#C4A96A",letterSpacing:2}}>Loading</div></div>,
  Material:  ()=> <div style={{background:"#FFF",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8}}><div style={{width:32,height:32,borderRadius:"50%",border:"3px solid #E8DEF8",borderTop:"3px solid #6750A4",animation:"spin 0.7s linear infinite"}}/><div style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:"#6750A4",fontWeight:700,letterSpacing:0.5}}>Loading…</div></div>,
  Newspaper: ()=> <div style={{background:"#F5F2E8",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:5}}><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:11,color:"#1A1A1A",letterSpacing:4,animation:"pulse 1.5s ease-in-out infinite"}}>◆◆◆</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#888",letterSpacing:3}}>LOADING</div></div>,
};

// ══════════════════════════════════════════════════════════════════════
// STAT — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Stats = {
  Brutalist: ()=> <div style={{background:"#FFFEF0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:1,borderTop:"4px solid #000"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,letterSpacing:3,color:"#888",textTransform:"uppercase"}}>Monthly Users</div><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:32,color:"#000",lineHeight:0.9,letterSpacing:1}}>24,801</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:7,color:"#FF4040",letterSpacing:2}}>↑ 18.4%</div></div>,
  Glass:     ()=> <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",padding:"10px"}}><div style={{background:"rgba(255,255,255,0.06)",backdropFilter:"blur(8px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:10,padding:"10px 14px",textAlign:"center"}}><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:300,fontSize:7,color:"rgba(255,255,255,0.5)",letterSpacing:2,marginBottom:4}}>REVENUE</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:18,color:"rgba(255,255,255,0.9)",letterSpacing:-0.5}}>$48.2K</div><div style={{fontSize:7,color:"#a78bfa",fontFamily:"'DM Mono',monospace",marginTop:3}}>↑ 22%</div></div></div>,
  Synthwave: ()=> <div style={{background:"#0D0021",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:2}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:3,color:"#00E5FF",textTransform:"uppercase"}}>SCORE</div><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:28,color:"#FF2D78",letterSpacing:2,textShadow:"0 0 12px #FF2D7888"}}>8,048,150</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#00E5FF",letterSpacing:2}}>HI-SCORE ↑</div></div>,
  Editorial: ()=> <div style={{background:"#FDF8F0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 14px",borderLeft:"3px solid #1A1A1A"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:4,color:"#888",textTransform:"uppercase",marginBottom:4}}>Subscribers</div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:24,color:"#1A1A1A",lineHeight:1,letterSpacing:-1}}>124K</div><div style={{width:20,height:1,background:"#1A1A1A",margin:"4px 0"}}/><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#888",letterSpacing:2}}>+3.2K THIS MONTH</div></div>,
  Playful:   ()=> <div style={{background:"linear-gradient(135deg,#FFF0F5,#F5F0FF)",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:4}}><div style={{fontSize:16}}>🎉</div><div style={{fontFamily:"'Righteous',sans-serif",fontSize:22,color:"#FF6B9D",letterSpacing:-0.5}}>10,248</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:300,fontSize:7,color:"#888"}}>Happy users this week</div></div>,
  Luxury:    ()=> <div style={{background:"#0F0E0A",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 14px",gap:3}}><div style={{fontFamily:"'Fraunces',serif",fontStyle:"italic",fontSize:6,letterSpacing:4,color:"#C4A96A",textTransform:"uppercase"}}>Portfolio Value</div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:22,color:"#C4A96A",letterSpacing:-0.5}}>€2.4M</div><div style={{width:24,height:1,background:"#C4A96A",opacity:0.5}}/></div>,
  Cyberpunk: ()=> <div style={{background:"#0A0A12",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 10px",gap:2}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,color:"#00FFFF",letterSpacing:3,opacity:0.7}}>NET_TRAFFIC</div><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:26,color:"#00FFFF",letterSpacing:2,textShadow:"0 0 10px #00FFFF88"}}>4.8 TB/s</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#FF2D78",letterSpacing:2}}>↑ OVERFLOW</div></div>,
  Soft:      ()=> <div style={{background:"#F0EEF8",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:4,padding:"8px"}}><div style={{width:50,height:50,borderRadius:"50%",background:"linear-gradient(135deg,#C9B8F0,#E8D4F0)",boxShadow:"3px 3px 10px #C9B8F066,-2px -2px 6px #FFF",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:12,color:"#5A4A7A"}}>94</div></div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:300,fontSize:7,color:"#9A8ABB"}}>Health Score</div></div>,
  Swiss:     ()=> <div style={{background:"#F2F0EB",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",borderBottom:"3px solid #E63311"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:4,color:"#888",textTransform:"uppercase",marginBottom:2}}>Visitors</div><div style={{fontFamily:"'Unbounded',sans-serif",fontWeight:900,fontSize:26,color:"#1A1A1A",letterSpacing:-1,lineHeight:1}}>82,410</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#E63311",letterSpacing:2,marginTop:2}}>+12% YOY</div></div>,
  DarkEdit:  ()=> <div style={{background:"#0E0E0C",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",borderBottom:"2px solid #C4A96A"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:4,color:"#C4A96A",marginBottom:3}}>READERSHIP</div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:22,color:"#F8F4EE",letterSpacing:-0.5}}>312,481</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#555",marginTop:2,letterSpacing:1}}>Monthly active</div></div>,
  Material:  ()=> <div style={{background:"#FFF",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",gap:3}}><div style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:"#49454E",letterSpacing:0.5}}>Monthly Revenue</div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:22,color:"#1C1B1F",letterSpacing:-0.5}}>$24,891</div><div style={{display:"flex",alignItems:"center",gap:4}}><div style={{width:6,height:6,borderRadius:"50%",background:"#386A20"}}/><div style={{fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:"#386A20",fontWeight:500}}>↑ 8.2% vs last month</div></div></div>,
  Newspaper: ()=> <div style={{background:"#F5F2E8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 12px",borderLeft:"3px solid #1A1A1A"}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:5,letterSpacing:3,color:"#888",textTransform:"uppercase",marginBottom:2}}>Circulation</div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,fontSize:22,color:"#1A1A1A",letterSpacing:-0.5}}>891,200</div><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:6,color:"#888",letterSpacing:1,marginTop:2}}>Daily print & digital</div></div>,
};

// ══════════════════════════════════════════════════════════════════════
// NAV ITEM — 12 styles
// ══════════════════════════════════════════════════════════════════════
const Navs = {
  Brutalist: ()=> <div style={{background:"#FFFEF0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",padding:"0 10px",gap:1,borderRight:"3px solid #000"}}>{["Work","About","Contact","Archive"].map((l,i)=><div key={i} style={{padding:"5px 6px",fontFamily:"'IBM Plex Mono',monospace",fontSize:9,letterSpacing:2,color:i===0?"#FFFEF0":"#000",background:i===0?"#000":"transparent",borderBottom:i>0?"1px solid #000":"none",cursor:"pointer",display:"flex",justifyContent:"space-between"}}>{l.toUpperCase()}{i===0&&<span>→</span>}</div>)}</div>,
  Glass:     ()=> <div style={{background:"linear-gradient(135deg,#1a1a2e,#16213e)",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:2,padding:"0 10px"}}>{["Dashboard","Analytics","Settings","Profile"].map((l,i)=><div key={i} style={{padding:"5px 8px",borderRadius:6,background:i===0?"rgba(124,58,237,0.25)":"transparent",border:i===0?"1px solid rgba(124,58,237,0.4)":"1px solid transparent",fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:i===0?"rgba(255,255,255,0.9)":"rgba(255,255,255,0.4)",cursor:"pointer",backdropFilter:i===0?"blur(4px)":"none",transition:"all 0.15s",display:"flex",gap:6,alignItems:"center"}}><span>{["◈","▣","⚙","◯"][i]}</span>{l}</div>)}</div>,
  Synthwave: ()=> <div style={{background:"#0D0021",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:3,padding:"0 10px"}}>{["HOME","LEVELS","SCORES","EXIT"].map((l,i)=><div key={i} style={{padding:"4px 8px",fontFamily:"'Bebas Neue',sans-serif",fontSize:10,letterSpacing:4,color:i===0?"#FF2D78":"#333",cursor:"pointer",borderLeft:i===0?"2px solid #FF2D78":"2px solid transparent",textShadow:i===0?"0 0 8px #FF2D7888":"none",transition:"all 0.15s"}}>{l}</div>)}</div>,
  Editorial: ()=> <div style={{background:"#FDF8F0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:0,padding:"0 10px",borderRight:"1px solid #E8E0D0"}}>{["Features","Reviews","Essays","Archive"].map((l,i)=><div key={i} style={{padding:"6px 0",fontFamily:i===0?"'Playfair Display',serif":"'IBM Plex Mono',monospace",fontStyle:i===0?"italic":"normal",fontSize:i===0?10:7,letterSpacing:i===0?0.5:2,color:i===0?"#1A1A1A":"#999",borderBottom:i<3?"1px solid #E8E0D0":"none",cursor:"pointer"}}>{l}</div>)}</div>,
  Playful:   ()=> <div style={{background:"linear-gradient(135deg,#FFF0F5,#F5F0FF)",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:4,padding:"0 8px"}}>{[{l:"🏠 Home",c:"#FF6B9D"},{l:"🎨 Create",c:"#B77FFF"},{l:"⭐ Saved",c:"#FFB347"},{l:"👤 Profile",c:"#4ECDC4"}].map((item,i)=><div key={i} style={{padding:"5px 10px",borderRadius:50,background:i===0?`${item.c}22`:"transparent",border:i===0?`2px solid ${item.c}`:"2px solid transparent",fontFamily:"'Righteous',sans-serif",fontSize:8,color:item.c,cursor:"pointer",transition:"all 0.15s"}}>{item.l}</div>)}</div>,
  Luxury:    ()=> <div style={{background:"#FAFAF8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:0,padding:"0 14px",borderRight:"1px solid #D4C4A0"}}>{["Maison","Collections","About","Contact"].map((l,i)=><div key={i} style={{padding:"7px 0",fontFamily:i===0?"'Playfair Display',serif":"'Fraunces',serif",fontStyle:"italic",fontSize:i===0?10:8,color:i===0?"#1A1A14":"#9A8A6A",borderBottom:i<3?"1px solid #E8E0D0":"none",cursor:"pointer",letterSpacing:i===0?0:1}}>{l}</div>)}</div>,
  Cyberpunk: ()=> <div style={{background:"#0A0A12",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:2,padding:"0 10px"}}>{["SYS_HOME","NET_SCAN","DATA_VIZ","LOG_OUT"].map((l,i)=><div key={i} style={{padding:"4px 8px",fontFamily:"'IBM Plex Mono',monospace",fontSize:7,letterSpacing:2,color:i===0?"#00FFFF":"#333",borderLeft:i===0?"1px solid #00FFFF":"1px solid transparent",cursor:"pointer",transition:"all 0.15s",boxShadow:i===0?"inset 6px 0 12px #00FFFF08":"none"}}>{l}</div>)}</div>,
  Soft:      ()=> <div style={{background:"#E8E4F0",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:4,padding:"0 8px"}}>{["Home","Explore","Favorites","Profile"].map((l,i)=><div key={i} style={{padding:"5px 10px",borderRadius:8,background:i===0?"#D8D0F0":"transparent",boxShadow:i===0?"2px 2px 6px #C0BCD4,-1px -1px 3px #FFF":"none",fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:i===0?"#5A4A7A":"#AAA",cursor:"pointer",transition:"all 0.15s",fontWeight:i===0?700:400}}>{l}</div>)}</div>,
  Swiss:     ()=> <div style={{background:"#F2F0EB",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:0,padding:"0 10px",borderRight:"2px solid #1A1A1A"}}>{["Work","Info","Contact","Shop"].map((l,i)=><div key={i} style={{padding:"6px 0",fontFamily:"'Unbounded',sans-serif",fontWeight:i===0?700:400,fontSize:i===0?9:7,color:i===0?"#E63311":"#1A1A1A",borderBottom:i<3?"1px solid #CCC":"none",cursor:"pointer",letterSpacing:i===0?0:-0.3}}>{l.toUpperCase()}</div>)}</div>,
  DarkEdit:  ()=> <div style={{background:"#0E0E0C",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:0,padding:"0 12px"}}>{["Features","Culture","Archive","About"].map((l,i)=><div key={i} style={{padding:"6px 0",fontFamily:i===0?"'Playfair Display',serif":"'IBM Plex Mono',monospace",fontStyle:i===0?"italic":"normal",fontSize:i===0?10:7,letterSpacing:i===0?0:2,color:i===0?"#C4A96A":"#444",borderBottom:i<3?"1px solid #1A1A18":"none",cursor:"pointer"}}>{l}</div>)}</div>,
  Material:  ()=> <div style={{background:"#FFF",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:1,padding:"0 8px"}}>{[{l:"Home",ic:"⬡"},{l:"Explore",ic:"◈"},{l:"Library",ic:"◫"},{l:"Profile",ic:"◯"}].map((item,i)=><div key={i} style={{padding:"6px 8px",borderRadius:8,background:i===0?"#EDE7F6":"transparent",fontFamily:"'Space Grotesk',sans-serif",fontSize:8,color:i===0?"#4F378B":"#49454E",cursor:"pointer",display:"flex",alignItems:"center",gap:7,fontWeight:i===0?700:400}}><span style={{fontSize:11,color:i===0?"#6750A4":"#79747E"}}>{item.ic}</span>{item.l}</div>)}</div>,
  Newspaper: ()=> <div style={{background:"#F5F2E8",height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",gap:0,padding:"0 10px",borderRight:"1px solid #1A1A1A"}}>{["News","Opinion","Sports","Culture"].map((l,i)=><div key={i} style={{padding:"5px 0",fontFamily:"'Playfair Display',serif",fontSize:8,color:i===0?"#1A1A1A":"#888",fontWeight:i===0?700:400,borderBottom:i<3?"1px solid #DDD":"none",cursor:"pointer",letterSpacing:0.5}}>{l}</div>)}</div>,
};

// ── Component registry ────────────────────────────────────────────────
const COMPONENTS = [
  {id:"button", label:"Button",    map:Buttons},
  {id:"card",   label:"Card",      map:Cards},
  {id:"input",  label:"Input",     map:Inputs},
  {id:"badge",  label:"Badge",     map:Badges},
  {id:"toggle", label:"Toggle",    map:Toggles},
  {id:"loader", label:"Loader",    map:Loaders},
  {id:"stat",   label:"Stat",      map:Stats},
  {id:"nav",    label:"Nav Item",  map:Navs},
];

const STYLE_KEYS = Object.keys(STYLES);
const STYLE_COLORS = {Brutalist:"#FF4040",Glass:"#7c3aed",Synthwave:"#FF2D78",Editorial:"#1A1A1A",Playful:"#FF6B9D",Luxury:"#C4A96A",Cyberpunk:"#00FFFF",Soft:"#C9B8F0",Swiss:"#E63311",DarkEdit:"#C4A96A",Material:"#6750A4",Newspaper:"#8B7355"};

// ── App ───────────────────────────────────────────────────────────────
export default function App(){
  const [compFilter, setCompFilter] = useState("ALL");
  const [styleFilter, setStyleFilter] = useState("ALL");
  const [expanded, setExpanded] = useState(null); // {compId, styleKey}

  const visibleComps = compFilter==="ALL" ? COMPONENTS : COMPONENTS.filter(c=>c.id===compFilter);
  const visibleStyles = styleFilter==="ALL" ? STYLE_KEYS : STYLE_KEYS.filter(s=>s===styleFilter);

  return <div style={{background:"#0A0A0A",minHeight:"100vh",paddingBottom:48}}>
    <style>{CSS}</style>

    {/* Header */}
    <div style={{borderBottom:"1px solid #1A1A1A",padding:"14px 16px 10px"}}>
      <div style={{fontSize:7,letterSpacing:4,color:"#444",marginBottom:4}}>STYLE MATRIX</div>
      <div style={{fontFamily:"'Unbounded',sans-serif",fontWeight:900,fontSize:16,color:"#F0EDE8",letterSpacing:-0.5,lineHeight:1.1}}>8 Components<br/>× 12 Styles</div>
      <div style={{fontSize:7,color:"#333",marginTop:4,letterSpacing:1}}>{visibleComps.length * visibleStyles.length} VARIANTS SHOWN</div>
    </div>

    {/* Component filter */}
    <div style={{padding:"10px 16px 6px",borderBottom:"1px solid #161616"}}>
      <div style={{fontSize:6,letterSpacing:3,color:"#333",marginBottom:6}}>COMPONENT</div>
      <div style={{display:"flex",gap:4,flexWrap:"wrap"}}>
        {["ALL",...COMPONENTS.map(c=>c.id)].map(id=>{
          const label=id==="ALL"?"ALL":COMPONENTS.find(c=>c.id===id)?.label;
          const active=compFilter===id;
          return <button key={id} onClick={()=>setCompFilter(id)} style={{padding:"4px 10px",borderRadius:1,fontSize:7,letterSpacing:1,border:`1px solid ${active?"#C4B8A8":"#1E1E1E"}`,color:active?"#C4B8A8":"#444",background:active?"#C4B8A810":"transparent",fontFamily:"'DM Mono',monospace",textTransform:"uppercase"}}>{label}</button>;
        })}
      </div>
    </div>

    {/* Style filter */}
    <div style={{padding:"8px 16px 10px",borderBottom:"1px solid #161616"}}>
      <div style={{fontSize:6,letterSpacing:3,color:"#333",marginBottom:6}}>STYLE</div>
      <div style={{display:"flex",gap:4,flexWrap:"wrap"}}>
        {["ALL",...STYLE_KEYS].map(sk=>{
          const active=styleFilter===sk;
          const c=STYLE_COLORS[sk]||"#888";
          return <button key={sk} onClick={()=>setStyleFilter(sk)} style={{padding:"4px 10px",borderRadius:1,fontSize:7,letterSpacing:0.5,border:`1px solid ${active?c+"88":"#1E1E1E"}`,color:active?c:"#444",background:active?`${c}10`:"transparent",fontFamily:"'DM Mono',monospace",display:"flex",alignItems:"center",gap:4,whiteSpace:"nowrap"}}>{sk!=="ALL"&&<span style={{width:5,height:5,borderRadius:"50%",background:c,display:"inline-block",flexShrink:0}}/>}{sk}</button>;
        })}
      </div>
    </div>

    {/* Expanded view */}
    {expanded&&(()=>{
      const comp=COMPONENTS.find(c=>c.id===expanded.compId);
      const Render=comp?.map[expanded.styleKey];
      const sc=STYLE_COLORS[expanded.styleKey]||"#888";
      return <div style={{margin:"10px 16px",border:"1px solid #2E2E2E",borderRadius:2,overflow:"hidden"}}>
        <div style={{height:180,background:"#0A0A0A",borderBottom:"1px solid #1A1A1A"}}>{Render&&<Render/>}</div>
        <div style={{padding:"10px 14px",background:"#111",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
          <div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>
            <div style={{fontFamily:"'Unbounded',sans-serif",fontWeight:700,fontSize:12,color:"#F0EDE8"}}>{comp?.label}</div>
            <span style={{padding:"2px 7px",borderRadius:1,fontFamily:"'DM Mono',monospace",fontSize:6,letterSpacing:2,border:`1px solid ${sc}44`,color:sc,background:`${sc}10`,textTransform:"uppercase"}}>{expanded.styleKey}</span>
          </div>
          <button onClick={()=>setExpanded(null)} style={{color:"#555",fontSize:14,padding:"2px 8px",border:"1px solid #222",borderRadius:1}}>×</button>
        </div>
      </div>;
    })()}

    {/* Matrix grid — each comp gets a section */}
    <div style={{padding:"8px 16px"}}>
      {visibleComps.map(comp=><div key={comp.id} style={{marginBottom:20}}>
        {/* Component label */}
        <div style={{fontFamily:"'DM Mono',monospace",fontSize:8,letterSpacing:3,color:"#555",marginBottom:8,textTransform:"uppercase",display:"flex",alignItems:"center",gap:8}}>
          <span>{comp.label}</span>
          <div style={{flex:1,height:1,background:"#1A1A1A"}}/>
          <span style={{color:"#2A2A2A"}}>{visibleStyles.length} styles</span>
        </div>
        {/* Row of style previews */}
        <div style={{display:"grid",gridTemplateColumns:`repeat(${Math.min(visibleStyles.length,4)},1fr)`,gap:5}}>
          {visibleStyles.map(sk=>{
            const Render=comp.map[sk];
            const sc=STYLE_COLORS[sk]||"#888";
            const isExp=expanded?.compId===comp.id&&expanded?.styleKey===sk;
            return <div key={sk} onClick={()=>setExpanded(isExp?null:{compId:comp.id,styleKey:sk})} style={{border:`1px solid ${isExp?sc+"88":"#1A1A1A"}`,borderRadius:2,overflow:"hidden",cursor:"pointer",transition:"border-color 0.15s",background:"#0A0A0A"}}>
              <div style={{height:70,overflow:"hidden",position:"relative"}}>
                {Render?<Render/>:<div style={{height:"100%",background:"#111",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:7,color:"#333",fontFamily:"'DM Mono',monospace"}}>—</span></div>}
                <div style={{position:"absolute",top:3,right:3,width:4,height:4,borderRadius:"50%",background:sc,opacity:0.7}}/>
              </div>
              <div style={{padding:"4px 6px",background:"#0E0E0E"}}><div style={{fontFamily:"'DM Mono',monospace",fontSize:6,color:"#555",letterSpacing:1,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{sk}</div></div>
            </div>;
          })}
        </div>
      </div>)}
    </div>
  </div>;
}
